### ISSUE TITLE
trivyOutputJson.forEach is not a function

### ISSUE THREAD

**Issue by craftyc0der** [Azure/container-scan#104]
I am having 100% failure rate with new and formerly functioning builds with this plugin. It exits with:
```
Error: trivyOutputJson.forEach is not a function
```
I've gone to other public repos that use this plugin and see the same errors in their pipelines that worked as late as yesterday afternoon.

Example:
https://github.com/StatCan/aaw-kubeflow-containers/runs/3815148249?check_suite_focus=true

**Comment by dagrover-dev** [comment]
I am also facing this issue. Since around 3:00am this morning all runs having been failing with the error given above. 

It seems a couple days ago trivy updated their json schema: https://github.com/aquasecurity/trivy/commit/b37f682ee243d4f7bf5ef83cca53d70aa36d7f5f

The error for me coincides with this commit: https://github.com/aquasecurity/trivy/commit/f12446d3ba26b89f5c443abcd5aee2bad2dea1c8

**Comment by spol-vt** [comment]
Same here, everything worked OK for weeks, then suddenly as of yesterday getting this error on every run.

**Comment by ajinkya599** [comment]
I have updated the action. Can someone please try and share if it works now?

**Comment by abelsromero** [comment]
> @abelsromero No OSS maintainer want to break compatibility, but most OSS, especially maintained for a long time, cannot avoid breaking change for improvements. Updating major version means breaking change in semver. Also, unstable versions might have it.

@knqyf263 OSS mantainer myself for years I am lost here. I am well aware of these practices and that why agree with you about pinning versions instead of using "latest" as you pointed out. Either that, or clearly state this is still in developemnt and subject to breakage to keep expectations, I am happy with any of those.

For context, I was suggested to use this action by an official Azure team to meet compliance requirements to deploy a product in Azure. Furthermore this action is under Azure org, and while it uses an OSS licences, it is a MS sponsored (or at least promoted) product, that why I'd expect a more stable product; not perfect, not fast response, not "fix my issue now", just that code does not change if I don't change the version I am pointing at. If this under a best-effort manteinance that should also be stated in the README.
