### ISSUE TITLE
README is out of sync with final spec.

### ISSUE THREAD

**Issue by ajinkya599** [Azure/container-scan#12]
README needs to be updated to be in sync with the final spec.

**Comment by shigupt202** [comment]
1. This should be replaced with image-name

![image](https://user-images.githubusercontent.com/57620559/79866603-a5815280-83fa-11ea-8a6e-2b277282a95c.png)

2. We should explicitly mention in README that checkout action should be used before container-scan action. Otherwise, even if whitelist file is present at right location, the action won't be able to read it.

**Comment by ds-ms** [comment]
Who changed this to `image-name` and why?
