### ISSUE TITLE
Inaccurate reports?

### ISSUE THREAD

**Issue by klautcomputing** [Azure/container-scan#25]
We are seeing CVEs getting reported here https://github.com/CovidShield/portal/runs/689671942
but our version should not be affected anymore see https://github.com/CovidShield/portal/blob/master/Gemfile.lock#L160
Any idea why that's happening?

**Comment by shigupt202** [comment]
@klautcomputing The action is detecting this `rake` vulnerability probably because some of the other gems that you're using, like `rack-proxy`, are using older versions of rake. 
This shows that the version of rake being used is much older: https://github.com/ncr/rack-proxy/blob/master/Gemfile.lock#L14
