### ISSUE TITLE
Strange placement of [container-scan] action in actions page

### ISSUE THREAD

**Issue by akphi** [Azure/container-scan#77]
Hi,

I have been using this action [in my project CI](https://github.com/finos/legend-studio/blob/master/.github/workflows/check-docker.yml#L37): here you `container-scan` is called within `Docker` workflow. However, I start noticing that if you go through my commit history, I start seeing `container-scan` showing up under other workflows. Take [this one](https://github.com/finos/legend-studio/runs/2404362593) for example, why is `[container-scan]` falls under `Node CI` in this case. You can also check [other commits' CI pipeline](https://github.com/finos/legend-studio/commits/master) and you would not find `[container-scan]` under `Docker` workflow like intended. Am I doing something wrong?

**Comment by akphi** [comment]
Hi, did you manage to take a look at this, I think this is still happening.

**Comment by ajinkya599** [comment]
Hi @akphi, I have raised this issue internally and it is being discussed. The source of the issue is the tight coupling between check runs and actions service. At this point, it is not clear how this problem can be solved. I will update this issue when I get  more details.

**Comment by akphi** [comment]
@ajinkya599 Thank you for your response! Could you mark this as a bug or do something to make this `non-stale`?

**Comment by akphi** [comment]
commenting to keep it non-stale

**Comment by ajinkya599** [comment]
Hi @akphi, We had a discussion with the checks/actions team on this.
This issue is inherent due to how the checks are designed, which is - each app gets its own check suite(s) and there is no way to associate a new check run to a particular check suite.
Unfortunately, this is not how the checks team expected it to be used and this behaviour cannot be incorporated in the design.

I would recommend you to install the scanitizer app. If you do so you would see all the scans under the scanitizer check which is a better experience. Also, with scanitizer you get the feature of updating the allowed-list if container-scan fails in your PR.

**Comment by akphi** [comment]
Sure thing! I don't quite get the explanation, but I take it as a `won't-fix` for now. I will try out `scanitizer` as you recommended. My question is though, currently I setup the scan in a github actions, if I install `scanitizer`, do I need to remove that action or so?
