### ISSUE TITLE
Action can't scan image when docker context is set

### ISSUE THREAD

**Issue by Smuu** [Azure/container-scan#85]
I logged in using the action `azure/docker-login@v1`. I would assume that this action then can scan images from the registry I logged in there.
But in fact I need to pass the `username` and `password` field for this action to scan images.

Edit: It seems, that Trivy uses the docker context but Dockle does not.

**Comment by ajinkya599** [comment]
As mentioned in the issue `Trivy` honours the Docker login context.
`Dockle` works if login is done using `docker login` command, however when `DOCKER_CONFIG` is set otherwise (ex. using `azure/docker-login` action), `Dockle` doesn't work as the path is not the default Docker config path.

There is an open issue on the Dockle repo:
https://github.com/goodwithtech/dockle/issues/87

@Smuu I would encourage you to re-iterate the ask on the Dockle issue.

**Comment by tomoyamachi** [comment]
@Smuu @ajinkya599 
I fixed it.
